import pytest
from django.urls import reverse
from rest_framework import status
from rest_framework.test import APIClient

from apps.users.models import User
from apps.categories.models import Category


@pytest.fixture
def api_client():
    return APIClient()


@pytest.fixture
def category(db):
    return Category.objects.create(name='Roses', description='Red and white roses')


@pytest.fixture
def admin_user(db):
    return User.objects.create_superuser(
        username='admin',
        email='admin@example.com',
        password='adminpass123',
    )


@pytest.mark.django_db
class TestCategoryList:
    def test_list_categories(self, api_client, category):
        url = reverse('category-list')
        response = api_client.get(url)
        assert response.status_code == status.HTTP_200_OK
        assert response.data['count'] == 1

    def test_slug_autogenerated(self, category):
        assert category.slug == 'roses'

    def test_get_category_by_slug(self, api_client, category):
        url = reverse('category-detail', kwargs={'slug': category.slug})
        response = api_client.get(url)
        assert response.status_code == status.HTTP_200_OK
        assert response.data['name'] == category.name


@pytest.mark.django_db
class TestCategoryPermissions:
    def test_create_anonymous_unauthorized(self, api_client):
        url = reverse('category-list')
        response = api_client.post(url, {'name': 'Tulips'}, format='json')
        assert response.status_code == status.HTTP_401_UNAUTHORIZED

    def test_create_requires_admin(self, api_client, db):
        regular_user = User.objects.create_user(
            username='regular',
            email='regular@example.com',
            password='pass123',
        )
        api_client.force_authenticate(user=regular_user)
        url = reverse('category-list')
        response = api_client.post(url, {'name': 'Tulips'}, format='json')
        assert response.status_code == status.HTTP_403_FORBIDDEN

    def test_admin_can_create(self, api_client, admin_user):
        api_client.force_authenticate(user=admin_user)
        url = reverse('category-list')
        response = api_client.post(url, {'name': 'Tulips'}, format='json')
        assert response.status_code == status.HTTP_201_CREATED
        assert Category.objects.filter(name='Tulips').exists()

    def test_admin_can_delete(self, api_client, admin_user, category):
        api_client.force_authenticate(user=admin_user)
        url = reverse('category-detail', kwargs={'slug': category.slug})
        response = api_client.delete(url)
        assert response.status_code == status.HTTP_204_NO_CONTENT
        assert not Category.objects.filter(pk=category.pk).exists()
