# Generated by Django 4.2.7 on 2026-06-28 15:10

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def seed_default_city(apps, schema_editor):
    City = apps.get_model('marketplace', 'City')
    City.objects.get_or_create(
        slug='tashkent',
        defaults={
            'name': 'Tashkent',
            'country': 'Uzbekistan',
            'currency': 'UZS',
            'is_active': True,
            'default_delivery_fee': Decimal('2.37'),
            'free_delivery_threshold': Decimal('39.53'),
        },
    )


def unseed_default_city(apps, schema_editor):
    City = apps.get_model('marketplace', 'City')
    City.objects.filter(slug='tashkent').delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_low_stock_threshold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('country', models.CharField(default='Uzbekistan', max_length=100, verbose_name='country')),
                ('currency', models.CharField(choices=[('UZS', "Uzbek so'm"), ('USD', 'US Dollar')], default='UZS', max_length=3, verbose_name='currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('2.37'), help_text='Stored in the backend base price unit.', max_digits=10, verbose_name='default delivery fee')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=Decimal('39.53'), help_text='Stored in the backend base price unit.', max_digits=10, verbose_name='free delivery threshold')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='code')),
                ('discount_type', models.CharField(choices=[('fixed_amount', 'Fixed amount'), ('percent', 'Percent')], max_length=20, verbose_name='discount type')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='discount value')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='minimum order amount')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='maximum discount amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='valid from')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='valid until')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='usage limit')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='used count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Promo code',
                'verbose_name_plural': 'Promo codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='commission percent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='marketplace.city', verbose_name='city')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('current_status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=20, verbose_name='current status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriers', to='marketplace.city', verbose_name='city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Courier',
                'verbose_name_plural': 'Couriers',
                'ordering': ['user__email'],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='products.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Wishlist item',
                'verbose_name_plural': 'Wishlist items',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.RunPython(seed_default_city, unseed_default_city),
    ]
