# Generated by Django 4.2.7 on 2026-06-12 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usermessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User message",
                "verbose_name_plural": "User messages",
            },
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="admin_reply",
            field=models.TextField(blank=True, verbose_name="admin reply"),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="body",
            field=models.TextField(verbose_name="message body"),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="is read"),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="replied_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="replied at"
            ),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="subject",
            field=models.CharField(max_length=200, verbose_name="subject"),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
