# Generated by Django 4.2.7 on 2026-06-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_usermessage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermessage",
            name="is_from_admin",
            field=models.BooleanField(default=False, verbose_name="is from admin"),
        ),
    ]
