# Generated by Codex on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_address_alter_user_email_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(default="Tashkent", max_length=80, verbose_name="city"),
        ),
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.CharField(
                choices=[("USD", "US Dollar"), ("UZS", "Uzbek so'm")],
                default="USD",
                max_length=3,
                verbose_name="currency",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("EN", "English"), ("RU", "Russian"), ("UZ", "Uzbek")],
                default="EN",
                max_length=2,
                verbose_name="language",
            ),
        ),
    ]
