# Generated by Codex on 2026-06-12

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_city_user_currency_user_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": _("A user with that username already exists."),
                },
                help_text=_("Required. 150 characters or fewer."),
                max_length=150,
                unique=True,
                verbose_name=_("username"),
            ),
        ),
    ]
