# Generated by Django 4.2.7 on 2026-06-27 11:40

from django.db import migrations, models
import django.db.models.deletion


def seed_delivery_zones(apps, schema_editor):
    DeliveryZone = apps.get_model('orders', 'DeliveryZone')
    zones = [
        {
            'name': 'Tashkent Center',
            'fee': '2.37',
            'description': 'Central Tashkent fixed delivery fee.',
            'requires_manual_confirmation': False,
        },
        {
            'name': 'Outer Tashkent',
            'fee': '3.56',
            'description': 'Outer city fixed delivery fee.',
            'requires_manual_confirmation': False,
        },
        {
            'name': 'Outside City',
            'fee': '0.00',
            'description': 'Staff confirms delivery availability and final fee.',
            'requires_manual_confirmation': True,
        },
    ]
    for zone in zones:
        DeliveryZone.objects.get_or_create(
            name=zone['name'],
            defaults={
                'fee': zone['fee'],
                'description': zone['description'],
                'requires_manual_confirmation': zone['requires_manual_confirmation'],
                'is_active': True,
            },
        )


def unseed_delivery_zones(apps, schema_editor):
    DeliveryZone = apps.get_model('orders', 'DeliveryZone')
    DeliveryZone.objects.filter(
        name__in=['Tashkent Center', 'Outer Tashkent', 'Outside City']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_call_recipient_before_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='name')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='fee')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('requires_manual_confirmation', models.BooleanField(default=False, verbose_name='requires manual confirmation')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('polygon', models.JSONField(blank=True, null=True, verbose_name='polygon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Delivery zone',
                'verbose_name_plural': 'Delivery zones',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_delivery_zones, unseed_delivery_zones),
        migrations.AddField(
            model_name='order',
            name='delivery_requires_confirmation',
            field=models.BooleanField(default=False, verbose_name='delivery requires confirmation'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='unpaid', max_length=20, verbose_name='payment status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online payment')], default='cash', max_length=20, verbose_name='payment method'),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('order_created', 'Order created'), ('order_confirmed', 'Order confirmed'), ('order_preparing', 'Order preparing'), ('courier_picked_up', 'Courier picked up'), ('order_delivered', 'Order delivered'), ('payment_status_changed', 'Payment status changed')], max_length=40, verbose_name='event')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('console', 'Console')], max_length=20, verbose_name='channel')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20, verbose_name='status')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Notification log',
                'verbose_name_plural': 'Notification logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.deliveryzone', verbose_name='delivery zone'),
        ),
    ]
