# Generated by Django 4.2.7 on 2026-06-28 15:10

from django.db import migrations, models
import django.db.models.deletion


def backfill_order_city(apps, schema_editor):
    City = apps.get_model('marketplace', 'City')
    DeliveryZone = apps.get_model('orders', 'DeliveryZone')
    Order = apps.get_model('orders', 'Order')
    city = City.objects.filter(slug='tashkent').first()
    if city:
        DeliveryZone.objects.filter(city__isnull=True).update(city=city)
        Order.objects.filter(city__isnull=True).update(city=city)


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('orders', '0007_order_payment_metadata_deliveryzone_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryzone',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_zones', to='marketplace.city', verbose_name='city'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.courier', verbose_name='assigned courier'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.city', verbose_name='city'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='courier assigned at'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_picked_up_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='courier picked up at'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='delivered at'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='discount amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_points_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='loyalty points earned'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.promocode', verbose_name='promo code'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.vendor', verbose_name='vendor'),
        ),
        migrations.RunPython(backfill_order_city, migrations.RunPython.noop),
    ]
