# Generated by Django 4.2.30 on 2026-09-09 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0009_notificationlog_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='created', max_length=20)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('external_payment_id', models.CharField(blank=True, default='', max_length=128)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=128)),
                ('checkout_url', models.URLField(blank=True, default='', max_length=2000)),
                ('failure_code', models.CharField(blank=True, default='', max_length=80)),
                ('failure_message', models.CharField(blank=True, default='', max_length=500)),
                ('provider_create_time', models.BigIntegerField(blank=True, null=True)),
                ('provider_perform_time', models.BigIntegerField(blank=True, null=True)),
                ('provider_cancel_time', models.BigIntegerField(blank=True, null=True)),
                ('cancellation_reason', models.SmallIntegerField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='inventory_released_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='inventory released at'),
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('provider', 'Provider'), ('customer', 'Customer'), ('admin', 'Admin'), ('system', 'System')], max_length=20)),
                ('event_type', models.CharField(max_length=80)),
                ('external_event_id', models.CharField(blank=True, default='', max_length=160)),
                ('status_from', models.CharField(blank=True, default='', max_length=20)),
                ('status_to', models.CharField(blank=True, default='', max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.paymentattempt')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
        migrations.AddConstraint(
            model_name='paymentevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_event_id', ''), _negated=True), fields=('payment', 'external_event_id'), name='unique_payment_external_event'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(fields=('order', 'provider', 'idempotency_key'), name='unique_payment_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('external_payment_id', ''), _negated=True), fields=('provider', 'external_payment_id'), name='unique_provider_external_payment_id'),
        ),
    ]
