# Generated by Django 4.2.30 on 2026-09-15 05:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_paymentattempt_order_inventory_released_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryzone',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='fee'),
        ),
    ]
