import type { BouquetPalette, BouquetSize, Category, Product, Review } from "./types";

/* ── shared palettes for the illustrated bouquets ─────────────── */

export const palettes = {
  pinkRose: {
    petals: ["#e8a2ae", "#d97f90", "#f2c4cb"],
    center: "#a84d60",
    backdrop: "linear-gradient(160deg,#fdf0f1 0%,#f7dcdf 100%)",
  },
  white: {
    petals: ["#fdfaf4", "#f3ecdf", "#faf4e9"],
    center: "#d9b96a",
    backdrop: "linear-gradient(160deg,#f8f4ec 0%,#ece4d2 100%)",
  },
  peony: {
    petals: ["#f4b8c4", "#ee9cb0", "#f9d3da"],
    center: "#c75a76",
    backdrop: "linear-gradient(160deg,#fdf1f4 0%,#f8dde3 100%)",
  },
  red: {
    petals: ["#c9474f", "#a82f3c", "#df6c70"],
    center: "#7c1f2b",
    backdrop: "linear-gradient(160deg,#fbeae8 0%,#f2cdc8 100%)",
  },
  lavender: {
    petals: ["#b9a8d8", "#9d87c7", "#d4c8e8"],
    center: "#6f5a9c",
    backdrop: "linear-gradient(160deg,#f4f0fa 0%,#e0d6ef 100%)",
  },
  tulip: {
    petals: ["#f2b748", "#e89a3c", "#f8d278"],
    center: "#b56a1e",
    backdrop: "linear-gradient(160deg,#fdf5e3 0%,#f5e2bc 100%)",
  },
  orchid: {
    petals: ["#e6d9f2", "#cdb4e4", "#f4eefa"],
    center: "#8f6bb8",
    backdrop: "linear-gradient(160deg,#f7f3fb 0%,#e7ddf1 100%)",
  },
  mixBox: {
    petals: ["#e8a2ae", "#f2b748", "#b9a8d8"],
    center: "#a84d60",
    backdrop: "linear-gradient(160deg,#fdf4ec 0%,#f6e0d3 100%)",
  },
  garden: {
    petals: ["#ee9cb0", "#f2b748", "#fdfaf4"],
    center: "#c75a76",
    backdrop: "linear-gradient(160deg,#f3f6ed 0%,#dfe8d4 100%)",
  },
  wedding: {
    petals: ["#fdfaf4", "#f2dfe4", "#efcdc6"],
    center: "#c0a26a",
    backdrop: "linear-gradient(160deg,#fbf8f2 0%,#eee4dc 100%)",
  },
  peachy: {
    petals: ["#ffb98a", "#f9966a", "#ffd5b3"],
    center: "#d96a35",
    backdrop: "linear-gradient(160deg,#fff3e8 0%,#fcdfc8 100%)",
  },
  fern: {
    petals: ["#8fbb8f", "#6da277", "#b5d3ae"],
    center: "#3f7351",
    backdrop: "linear-gradient(160deg,#eff6ec 0%,#d8e8d2 100%)",
  },
  sky: {
    petals: ["#a9c8e8", "#86aedd", "#cfe1f3"],
    center: "#4f74a8",
    backdrop: "linear-gradient(160deg,#eff5fb 0%,#d9e7f4 100%)",
  },
} satisfies Record<string, BouquetPalette>;

/* ── bouquet sizes ────────────────────────────────────────────── */

export const bouquetSizes: BouquetSize[] = [
  { id: "S", label: "Small", multiplier: 0.75 },
  { id: "M", label: "Standard", multiplier: 1 },
  { id: "L", label: "Luxe", multiplier: 1.4 },
];

/* ── catalog products ─────────────────────────────────────────── */

export const products: Product[] = [
  {
    id: "pink-rose-harmony",
    name: "Pink Rose Harmony",
    shop: "Atelier Bloom",
    price: 49,
    oldPrice: 58,
    rating: 4.9,
    reviews: 214,
    category: "roses",
    deliveryMins: 90,
    deliveryToday: true,
    isNew: false,
    popularity: 98,
    description:
      "Eleven garden roses in three shades of pink, softened with eustoma and a cloud of gypsophila. Wrapped in double kraft with a satin ribbon.",
    composition: ["11 pink roses", "Eustoma", "Gypsophila", "Kraft wrap & ribbon"],
    hasSizes: true,
    palette: palettes.pinkRose,
  },
  {
    id: "peach-sorbet",
    name: "Peach Sorbet Bouquet",
    shop: "Atelier Bloom",
    price: 52,
    rating: 4.9,
    reviews: 73,
    category: "mono",
    deliveryMins: 80,
    deliveryToday: true,
    isNew: true,
    popularity: 92,
    description:
      "Our signature house bouquet — apricot spray roses and peach ranunculus that melt into each other like sorbet on a summer evening.",
    composition: ["9 apricot spray roses", "7 peach ranunculus", "Salal greens", "Wax paper wrap"],
    hasSizes: true,
    palette: palettes.peachy,
  },
  {
    id: "romantic-red",
    name: "Romantic Red Roses",
    shop: "Atelier Bloom",
    price: 75,
    rating: 4.9,
    reviews: 322,
    category: "romantic",
    deliveryMins: 60,
    deliveryToday: true,
    isNew: false,
    popularity: 100,
    description:
      "Fifteen velvet Ecuador roses on long stems — the classic that never misses. Includes a handwritten card on request.",
    composition: ["15 red Ecuador roses 60cm", "Ruscus", "Matte film wrap", "Free card"],
    hasSizes: true,
    palette: palettes.red,
  },
  {
    id: "white-dream",
    name: "White Dream Bouquet",
    shop: "Bahor Flowers",
    price: 64,
    rating: 4.8,
    reviews: 167,
    category: "roses",
    deliveryMins: 110,
    deliveryToday: true,
    isNew: false,
    popularity: 91,
    description:
      "Airy white roses and chamomile with eucalyptus — light, calm and perfect when you don't know their favorite color (white always works).",
    composition: ["9 white roses", "Chamomile", "Eucalyptus", "Cotton ribbon"],
    hasSizes: true,
    palette: palettes.white,
  },
  {
    id: "peony-cloud",
    name: "Peony Cloud",
    shop: "Chinor Garden",
    price: 89,
    oldPrice: 105,
    rating: 5.0,
    reviews: 96,
    category: "mono",
    deliveryMins: 140,
    deliveryToday: false,
    isNew: true,
    popularity: 95,
    description:
      "Seven coral-pink peonies at the perfect half-open stage. They will fully open within 24 hours and stay fluffy for about a week.",
    composition: ["7 coral peonies", "Pistache greens", "Silk wrap"],
    hasSizes: true,
    palette: palettes.peony,
  },
  {
    id: "scarlet-101",
    name: "101 Red Roses",
    shop: "Lola Market",
    price: 189,
    oldPrice: 220,
    rating: 5.0,
    reviews: 58,
    category: "roses",
    deliveryMins: 150,
    deliveryToday: true,
    isNew: false,
    popularity: 89,
    description:
      "The grand gesture. One hundred and one red roses hand-tied into a metre-wide dome. Delivered by two couriers, photo before handover included.",
    composition: ["101 red roses 50cm", "Oversize kraft wrap", "Velvet ribbon"],
    hasSizes: false,
    palette: palettes.red,
  },
  {
    id: "sunshine-tulips",
    name: "Sunshine Tulips",
    shop: "Lola Market",
    price: 39,
    oldPrice: 46,
    rating: 4.8,
    reviews: 145,
    category: "mono",
    deliveryMins: 70,
    deliveryToday: true,
    isNew: false,
    popularity: 87,
    description:
      "Twenty-one yellow tulips straight from a Tashkent greenhouse — picked the same morning they ship. Instant serotonin.",
    composition: ["21 yellow tulips", "Kraft wrap", "Raffia tie"],
    hasSizes: true,
    palette: palettes.tulip,
  },
  {
    id: "first-date",
    name: "First Date Mix",
    shop: "Sayyora Studio",
    price: 42,
    rating: 4.7,
    reviews: 64,
    category: "romantic",
    deliveryMins: 85,
    deliveryToday: true,
    isNew: true,
    popularity: 81,
    description:
      "Sweet but not too serious: pink spray roses, white freesia and a sprig of lavender. Sized to carry through a cafe door without knocking cups over.",
    composition: ["7 pink spray roses", "White freesia", "Lavender sprigs", "Paper lace wrap"],
    hasSizes: true,
    palette: palettes.peony,
  },
  {
    id: "velvet-box",
    name: "Velvet Rose Box",
    shop: "Bahor Flowers",
    price: 78,
    rating: 4.9,
    reviews: 112,
    category: "box",
    deliveryMins: 100,
    deliveryToday: true,
    isNew: false,
    popularity: 88,
    description:
      "Roses and ranunculus arranged in floral foam inside a round velvet hatbox — zero vase required, stays fresh up to ten days with watering.",
    composition: ["Roses & ranunculus", "Eucalyptus", "Velvet hatbox", "Care instructions"],
    hasSizes: true,
    palette: palettes.mixBox,
  },
  {
    id: "birthday-box",
    name: "Birthday Flower Box",
    shop: "Lola Market",
    price: 59,
    rating: 4.8,
    reviews: 198,
    category: "birthday",
    deliveryMins: 90,
    deliveryToday: true,
    isNew: false,
    popularity: 93,
    description:
      "A confetti-bright mix of roses, tulips and chrysanthemums in a kraft box, topped with a cake-style topper that reads “Happy B-Day”.",
    composition: ["Mixed seasonal flowers", "Kraft box", "B-Day topper", "Free card"],
    hasSizes: true,
    palette: palettes.mixBox,
  },
  {
    id: "lavender-basket",
    name: "Lavender Basket",
    shop: "Sayyora Studio",
    price: 54,
    rating: 4.7,
    reviews: 88,
    category: "baskets",
    deliveryMins: 120,
    deliveryToday: false,
    isNew: true,
    popularity: 74,
    description:
      "A woven willow basket of lavender, lisianthus and seeded eucalyptus. Smells like Provence; lasts like a houseplant.",
    composition: ["Lavender", "Purple lisianthus", "Seeded eucalyptus", "Willow basket"],
    hasSizes: false,
    palette: palettes.lavender,
  },
  {
    id: "mothers-garden",
    name: "Mother's Garden Basket",
    shop: "Chinor Garden",
    price: 69,
    oldPrice: 79,
    rating: 4.9,
    reviews: 124,
    category: "baskets",
    deliveryMins: 95,
    deliveryToday: true,
    isNew: false,
    popularity: 85,
    description:
      "Garden roses, matthiola and daisies gathered loosely the way flowers grow — warm, generous and unmistakably for mom.",
    composition: ["Garden roses", "Matthiola", "Daisies", "Garden basket"],
    hasSizes: false,
    palette: palettes.garden,
  },
  {
    id: "premium-wedding",
    name: "Premium Wedding Bouquet",
    shop: "Bahor Flowers",
    price: 149,
    rating: 5.0,
    reviews: 47,
    category: "wedding",
    deliveryMins: 180,
    deliveryToday: false,
    isNew: true,
    popularity: 82,
    description:
      "Ivory O'Hara roses, white orchid blooms and trailing greenery, hand-wired for an all-day hold. Includes a matching boutonnière.",
    composition: ["O'Hara roses", "Phalaenopsis blooms", "Trailing ruscus", "Boutonnière included"],
    hasSizes: false,
    palette: palettes.wedding,
  },
  {
    id: "orchid-elegance",
    name: "Orchid in Ceramic Pot",
    shop: "Sayyora Studio",
    price: 96,
    rating: 4.9,
    reviews: 61,
    category: "plants",
    deliveryMins: 130,
    deliveryToday: false,
    isNew: true,
    popularity: 79,
    description:
      "A double-stem white phalaenopsis in a matte ceramic pot. Blooms for up to three months — the gift that quietly keeps going.",
    composition: ["Double-stem phalaenopsis", "Matte ceramic pot", "Care guide"],
    hasSizes: false,
    palette: palettes.orchid,
  },
  {
    id: "emerald-fern",
    name: "Emerald Fern in Pot",
    shop: "Chinor Garden",
    price: 32,
    rating: 4.6,
    reviews: 53,
    category: "plants",
    deliveryMins: 110,
    deliveryToday: true,
    isNew: false,
    popularity: 67,
    description:
      "A lush Boston fern in a terracotta pot — air-purifying, pet-safe and very hard to kill. Great for desks and first apartments.",
    composition: ["Boston fern", "Terracotta pot", "Pet-safe", "Care guide"],
    hasSizes: false,
    palette: palettes.fern,
  },
  {
    id: "choco-bliss",
    name: "Chocolate & Blooms Set",
    shop: "Lola Market",
    price: 45,
    oldPrice: 52,
    rating: 4.8,
    reviews: 139,
    category: "gifts",
    deliveryMins: 75,
    deliveryToday: true,
    isNew: false,
    popularity: 84,
    description:
      "A petite peach bouquet paired with a 12-piece box of Belgian pralines. The safe bet that still feels personal.",
    composition: ["Mini peach bouquet", "12 Belgian pralines", "Gift bag & card"],
    hasSizes: false,
    palette: palettes.peachy,
  },
  {
    id: "cloud-nine-balloons",
    name: "Cloud Nine Balloon Bunch",
    shop: "Sayyora Studio",
    price: 25,
    rating: 4.7,
    reviews: 91,
    category: "balloons",
    deliveryMins: 60,
    deliveryToday: true,
    isNew: false,
    popularity: 72,
    description:
      "Nine pastel latex and chrome balloons on weighted ribbons — peach, cream and sky blue. Floats for 3–5 days.",
    composition: ["9 helium balloons", "Pastel palette", "Weighted ribbons"],
    hasSizes: false,
    palette: palettes.sky,
  },
];

/* ── category chips ───────────────────────────────────────────── */

export const categories: Category[] = [
  { id: "roses", name: "Розы", tint: "#fde7ec" },
  { id: "mono", name: "Монобукеты", tint: "#fff0db" },
  { id: "box", name: "Цветы в коробке", tint: "#ffeadb" },
  { id: "baskets", name: "Корзины", tint: "#f1ecdf" },
  { id: "birthday", name: "День рождения", tint: "#fde9e0" },
  { id: "romantic", name: "Романтика", tint: "#fbe3e7" },
  { id: "wedding", name: "Свадьба", tint: "#f5efe6" },
  { id: "plants", name: "Растения", tint: "#e6f3ea" },
  { id: "gifts", name: "Подарки", tint: "#f0ebfa" },
  { id: "balloons", name: "Шары", tint: "#e9f2fb" },
];

/* ── reviews ──────────────────────────────────────────────────── */

export const reviews: Review[] = [
  {
    id: "r1",
    name: "Madina K.",
    date: "May 28, 2026",
    rating: 5,
    text: "Ordered at noon, delivered by 2pm with a photo before handover. The peonies were even fresher than the picture — my mom cried happy tears.",
    shop: "Chinor Garden",
    palette: palettes.peony,
  },
  {
    id: "r2",
    name: "Timur A.",
    date: "June 2, 2026",
    rating: 5,
    text: "The photo-before-delivery feature saved me. I asked to swap the ribbon color and the florist did it in minutes. Flawless anniversary.",
    shop: "Atelier Bloom",
    palette: palettes.red,
  },
  {
    id: "r3",
    name: "Nilufar S.",
    date: "June 7, 2026",
    rating: 4,
    text: "Beautiful tulips and very fast courier — 40 minutes across the whole city. Would love more vase options at checkout.",
    shop: "Lola Market",
    palette: palettes.tulip,
  },
  {
    id: "r4",
    name: "Sardor R.",
    date: "June 10, 2026",
    rating: 5,
    text: "Ordered the Peach Sorbet for our rehearsal dinner. It looked far more expensive than it cost and matched the venue perfectly.",
    shop: "Atelier Bloom",
    palette: palettes.peachy,
  },
  {
    id: "r5",
    name: "Kamila Y.",
    date: "June 4, 2026",
    rating: 5,
    text: "The velvet rose box survived a 30-minute taxi ride and still looked showroom-perfect a week later. Watering instructions actually work.",
    shop: "Bahor Flowers",
    palette: palettes.mixBox,
  },
  {
    id: "r6",
    name: "Bekzod T.",
    date: "May 30, 2026",
    rating: 5,
    text: "Balloons plus the fern as a desk-warming gift — both arrived together, on time, with a photo. My colleague was delighted.",
    shop: "Sayyora Studio",
    palette: palettes.fern,
  },
];
