# Generated by Django 4.2.7 on 2026-06-28 15:10

from django.db import migrations, models
import django.db.models.deletion


def backfill_product_city(apps, schema_editor):
    City = apps.get_model('marketplace', 'City')
    Product = apps.get_model('products', 'Product')
    city = City.objects.filter(slug='tashkent').first()
    if city:
        Product.objects.filter(city__isnull=True).update(city=city)


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('products', '0003_product_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketplace.city', verbose_name='city'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketplace.vendor', verbose_name='vendor'),
        ),
        migrations.RunPython(backfill_product_city, migrations.RunPython.noop),
    ]
